name: release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install packages
        run: yarn install

      - name: format
        run: yarn nx format:check --all

      - name: lint
        run: yarn nx run-many --target=lint --all --parallel

      - name: test
        run: yarn nx run-many --target=test --all --parallel

      - name: build - production
        run: yarn nx run-many --target=build --all --parallel --configuration=production

      - name: Deploy dive-production
        uses: appleboy/scp-action@v0.0.10
        if: startsWith(github.ref, 'refs/tags/dive-v')
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
          source: 'dist/apps/dive'
          target: '${{ secrets.DIVE_PRODUCTION_DIRECTORY }}'
          strip_components: 3

      - name: Deploy planty-production
        uses: appleboy/scp-action@v0.0.10
        if: startsWith(github.ref, 'refs/tags/planty-v')
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
          source: 'dist/apps/planty'
          target: '${{ secrets.PLANTY_PRODUCTION_DIRECTORY }}'
          strip_components: 3

      - name: Deploy ais-production
        uses: appleboy/scp-action@v0.0.10
        if: startsWith(github.ref, 'refs/tags/ais-v')
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
          source: 'dist/apps/ais'
          target: '${{ secrets.AIS_PRODUCTION_DIRECTORY }}'
          strip_components: 3

      - name: Deploy geomat-production
        uses: appleboy/scp-action@v0.0.10
        if: startsWith(github.ref, 'refs/tags/geomat-v')
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
          source: 'dist/apps/geomat'
          target: '${{ secrets.GEOMAT_PRODUCTION_DIRECTORY }}'
          strip_components: 3

      - name: Deploy wabe-production
        uses: appleboy/scp-action@v0.0.10
        if: startsWith(github.ref, 'refs/tags/wabe-v')
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          rm: true
          source: 'dist/apps/wabe'
          target: '${{ secrets.WABE_PRODUCTION_DIRECTORY }}'
          strip_components: 3
